KEYWORDS_FILE = "Database/suspicious_keywords.txt"
TRUSTED_DOMAINS = "Database/trusted_domains.txt"
URL_PATTERNS = "Database/url_patterns.txt"
ATTACHMENT_KEYWORDS = "Database/attachment_keywords.txt"
GRAMMAR_PATTERNS = "Database/grammar_patterns.txt"
URGENCY_PATTERNS = "Database/urgency_patterns.txt"
SPOOFING_PATTERNS = "Database/spoofing_patterns.txt"
MALICIOUS_DOMAINS = "Database/malicious_domains.txt"